### ISSUE TITLE
Doesn't work on Expo managed workflow ?

### ISSUE THREAD

**Issue by ErkanGorgulu** [Fitpassu/react-native-stripe-payments#12]
I tried to implement this on my project but got the error on the image. Any idea what i should use for stripe payment intent api ?

![1601545412125](https://user-images.githubusercontent.com/16388246/94794106-184c1c00-03e4-11eb-962b-6ddacc80c23d.jpg)

**Comment by viktorasl** [comment]
I've not tried running using expo managed workflow and surely nothing was done to support that if needed, feel free to contribute!

**Comment by abdulrehmanhw** [comment]
good hogya

**Comment by viktorasl** [comment]
I believe expo does not support inclusion of native code
> https://docs.expo.io/introduction/faq/
> How do I add custom native code to my Expo project?
> Managed Expo projects don't support custom native code
