### ISSUE TITLE
No option for payment amount?

### ISSUE THREAD

**Issue by calliday** [Fitpassu/react-native-stripe-payments#16]
The ReadMe shows the code necessary for completing a One-Time Payment, but does not show how to insert the amount. How do we submit the amount to be paid to the Stripe account?

**(Example from the ReadMe)**
`import stripe from 'react-native-stripe-payments';

const cardDetails = {
  number: '4242424242424242',
  expMonth: 10,
  expYear: 21,
  cvc: '888',
}
stripe.confirmPayment('client_secret_from_backend', cardDetails)
  .then(result => {
    // result of type PaymentResult
  })
  .catch(err =>
    // error performing payment
  )`

**Comment by viktorasl** [comment]
Please follow SCA payment flow (https://stripe.com/docs/payments/accept-a-payment?integration=elements#ios-create-server-side) where you will have to initiate payment with correct payment amount.

**Comment by calliday** [comment]
Thank you @viktorasl , I was naively thinking too simply of the process. For others like me, it would help if the readme was updated to make it more clear that the use of this package is in combination with the PaymentIntent.
