### ISSUE TITLE
Component Exception: null is not an object (evaluating 'StripePayments.init')

### ISSUE THREAD

**Issue by sunnydonaldson** [Fitpassu/react-native-stripe-payments#21]
When calling `stripe.setOptions(publishingKey(publicKey))` Component Exception error: null is not an object (evaluating 'StripePayments.init')

**Comment by viktorasl** [comment]
Hi, are you initializing SDK by calling `stripe.setOptions({ publishingKey: 'STRIPE_PUBLISHING_KEY' });` ?

**Comment by sunnydonaldson** [comment]
Yeah, exactly like that, as an object.  Does it matter where I initialise it?

**Comment by viktorasl** [comment]
Nope. But `null is not an object` indicates that somewhere it's not being passed as an object. I'm just wondering if `{publishingKey: "..."}`

**Comment by sunnydonaldson** [comment]
Okay, thanks so much for your help.  In the end, it was a mistake I made when duplicating one of my projects, I forgot to rename some the Xcode files.
