### ISSUE TITLE
CocoaPods could not find compatible versions for pod "react-native-stripe-payments"

### ISSUE THREAD

**Issue by Warkey1991** [Fitpassu/react-native-stripe-payments#22]
[!] CocoaPods could not find compatible versions for pod "react-native-stripe-payments":
  In Podfile:
    react-native-stripe-payments (from `../node_modules/react-native-stripe-payments`)

Specs satisfying the `react-native-stripe-payments (from `../node_modules/react-native-stripe-payments`)` dependency were found, but they required a higher minimum deployment target.

Xcode: 12.2

**Comment by Duboox** [comment]
Same here

**Comment by Billmike** [comment]
Same issue

**Comment by akhilsanker** [comment]
Same issue,
any solution?

**Comment by rameshvishnoi90904** [comment]
update ios platform version to 11 in Podfile
![image](https://user-images.githubusercontent.com/13585002/106132898-90580200-618a-11eb-8912-1c2e4c64066a.png)

**Comment by leokulakao** [comment]
Update ios platform version to 12 in Podfile. It is working!!!

**Comment by viktorasl** [comment]
Yep, it's related to Xcode project's deployment target being lower than 11.0 (which is deployment target for this library)

**Comment by Shamrockhub** [comment]
Yeah ..Thanks its works changing it to 12.0
