### ISSUE TITLE
TypeError: null is not an object (evaluating 'StripePayments.init')

### ISSUE THREAD

**Issue by birhanuh** [Fitpassu/react-native-stripe-payments#26]
Getting TypeError: null is not an object (evaluating 'StripePayments.init') after installing the module. 

Version: ^1.0.6

<img width="1098" alt="Screenshot 2021-03-29 at 16 11 16" src="https://user-images.githubusercontent.com/5165981/112841743-89c20a00-90a9-11eb-835f-2fd3adfb5f21.png">

**Comment by viktorasl** [comment]
I believe you've forgotten to install native dependencies
