### ISSUE TITLE
LocalizableStrings issues on iOS

### ISSUE THREAD

**Issue by davidecastello** [Fitpassu/react-native-stripe-payments#3]
Hi! 
Your library is great, but we can't seem to be able to localize to strings on iOS. 
It seems like it's not really finding the Bundle or the associated LocalizableStrings. 

We are using the latest versions. Are we missing something? 
Can you help us, please?

Thanks.

**Comment by davidecastello** [comment]
We figured it out by looking at this issue: https://github.com/tipsi/tipsi-stripe/issues/97

We removed "Use Base Internationalization", added the language that we wanted (italian) and added also two Localizable.strings files (en, it).

**Comment by viktorasl** [comment]
I'm happy you found the solution!

**Comment by francesco-clementi-92** [comment]
Hi @davidecastello, 

could you please share more details about how you figured out, please?

How can I follow the steps you mentioned?

**Comment by davidecastello** [comment]
Hi @missklorina, 

I checked for the "Localizable.strings" file (for the language I was looking for, in my case "Italian") inside the "Stripe" pod.
 
![Schermata 2020-08-07 alle 10 08 01](https://user-images.githubusercontent.com/14249532/89624332-5c181e80-d896-11ea-8d4a-01e9be2903c8.png)

Once I made sure they were actually there, I tried to figure out a way to get the app to find them and use them. 

I found a similar issue on the tipsi library, you can check it out: https://github.com/tipsi/tipsi-stripe/issues/97

Therefore, under Project > Info, I removed the check for "Use Base Internationalization" and under "Localizations" I added the Italian language. 

![Schermata 2020-08-07 alle 10 08 23](https://user-images.githubusercontent.com/14249532/89624645-d779d000-d896-11ea-98bd-1d87ca3ed247.png)

If you want to check for yourself and debug something, you can check out the method `localizedStripeStringForKey` inside the class `STPLocalizationUtils`, inside the Stripe pod.
Make sure to use the latest version of Stripe. 

Let me know if you need any more help. :v:
