### ISSUE TITLE
Project scope?

### ISSUE THREAD

**Issue by zRelux** [Fitpassu/react-native-stripe-payments#30]
Hey man good idea of making a new stripe library.
I was wondering do you see the future of the library be a replacement for `tipsi-stripe` if yes I would love to help in any way. even though my knowledge is mostly `ts`.
Maybe it would be good if you added stuff in the projects tab so people could see what you are working on

**Comment by gax97** [comment]
Stripe will soon release their official react-native library.

**Comment by zRelux** [comment]
Source?

**Comment by Sheharyar566** [comment]
@gax97  any thoughts about what's the minimum time it'll take them to release the lib?
