### ISSUE TITLE
Library gives an error

### ISSUE THREAD

**Issue by OmarGulzar** [Fitpassu/react-native-stripe-payments#31]
PaymentConfiguration was not initialized
![Screenshot_20210415-145022](https://user-images.githubusercontent.com/33081046/114846302-31557100-9dfa-11eb-85c0-da88e11c9270.jpg)

**Comment by viktorasl** [comment]
you did not call `stripe.setOptions({ publishingKey: 'STRIPE_PUBLISHING_KEY' })` or at least did not call early enough

**Comment by OmarGulzar** [comment]
I did
early enough not sure about that, let me check. 
Between thank you for responding

**Comment by OmarGulzar** [comment]
The issue still persists, Please help, Where do you suggest i call stripe.setOptions() ?

**Comment by viktorasl** [comment]
Could you try calling `stripe.setOptions({ publishingKey: 'STRIPE_PUBLISHING_KEY' })` i.e in `componentDidMount` and `confirmPayment` on button click

**Comment by OmarGulzar** [comment]
That is exactly what i am doing. But with no luck

**Comment by viktorasl** [comment]
Hm, well, not quite sure how to help now, no ideas at the moment

**Comment by OmarGulzar** [comment]
The issue was related to something else, some debug mode issue.
