### ISSUE TITLE
'new' is unavailable: You cannot directly instantiate an STPIssuingCardPin 

### ISSUE THREAD

**Issue by ashrafzidane13** [Fitpassu/react-native-stripe-payments#35]
every thing work ok but when i update the xcode to 14.5 this error in STPIssuingCardPin in this package react-native-stripe-payments so i search about the problem and its because this package attend on stripe version 19 but need to upgrade to 24.1

so what i have to do

**Comment by viktorasl** [comment]
Sorry, that was related to Stripe library native code.
I've released 1.1.0 lib version with Stripe 20.x iOS and Android support. Although I recommend migrating to official Stripe RN library.
