### ISSUE TITLE
Update version 14.2.1 of the SDK Stripe Android SDK (com.stripe: stripe-android) version 16.9.0, For security reasons according to Google

### ISSUE THREAD

**Issue by cerezagroup** [Fitpassu/react-native-stripe-payments#40]
Please update version 14.2.1 of the Stripe Android SDK (com.stripe: stripe-android) to version 16.9.0, because Google Play won't let me upload the apk for security reasons.

the reason from the Google Play part is as follows:
-----------------
Version 14.2.1 of the Stripe Android SDK (com.stripe: stripe-android) makes it easy to transmit or collect personal and sensitive information. This feature must meet the Google Play Disclosure and Consent Notices Visibility Requirements, as well as the applicable privacy policy requirements outlined in the User Data policy. You cannot publish this version due to a problem with this  @policy.

In order to publish it, **we recommend that you update the SDK to version 16.9.0, the one recommended by the SDK provider**. For more information, contact the vendor of the SDK.

If you have reviewed the policy and you think we made this decision in error, please contact our Policy Support team.

------------------------------------

Thank you very much @Fitpassu, for that great library, although stripe recently released a library with support for react native 👍

**Comment by dimaportenko** [comment]
I patched the library with https://www.npmjs.com/package/patch-package
```
diff --git a/node_modules/react-native-stripe-payments/android/build.gradle b/node_modules/react-native-stripe-payments/android/build.gradle
index e0585e9..3448135 100644
--- a/node_modules/react-native-stripe-payments/android/build.gradle
+++ b/node_modules/react-native-stripe-payments/android/build.gradle
@@ -73,7 +73,7 @@ repositories {
 dependencies {
     //noinspection GradleDynamicVersion
     implementation 'com.facebook.react:react-native:+'  // From node_modules
-    implementation 'com.stripe:stripe-android:14.2.1'
+    implementation 'com.stripe:stripe-android:16.9.0'
 }
 
 def configureReactNativePom(def pom) {
```

Looks like it solves the issue for me but I'm not sure it doesn't break anything.

**Comment by krinish291** [comment]
I have updated the SDK(16.9.0) and .gradle(3.5.4) it works for me. [(PR)](https://github.com/Fitpassu/react-native-stripe-payments/pull/41)
