### ISSUE TITLE
My app is getting crashed when I'm trying to make payment!

### ISSUE THREAD

**Issue by octocat01** [Fitpassu/react-native-stripe-payments#6]
My app is getting crashed when I'm trying to pay using test credentials.
I'm getting card valid to true but not when I go to confirmPayment app crashes without any log or error.

```
stripe.confirmPayment('client_secret_from_backend', cardDetails)
  .then(result => {
    console.log("result ", result)
  })
  .catch(err =>
    console.log("err ", err)
  )
```

**Comment by viktorasl** [comment]
Hey! What does the cash log say? I believe you should see stack of native crash log (either on iOS or Android)

**Comment by octocat01** [comment]
@viktorasl hey sorry, I did not get any log at that time and then I didn't get time to check stack as I integrated stripe API directly.

**Comment by nlabofa** [comment]
same issue here. why was this closed ? @octocat01 @viktorasl

**Comment by octocat01** [comment]
@nlabofa I closed this issue as I've integrated stripe API directly.

But if you could provide stack of native it would be helpful for debugging, as mentioned by viktorasl "Hey! What does the cash log say? I believe you should see stack of native crash log (either on iOS or Android)"

**Comment by viktorasl** [comment]
There is a similar issue (https://github.com/Fitpassu/react-native-stripe-payments/issues/18), maybe you were using `secret key` instead of `publishable key` as well?
