### ISSUE TITLE
what is client_secret_from_backend ?

### ISSUE THREAD

**Issue by mohamad-gadgetapp** [Fitpassu/react-native-stripe-payments#7]

**Comment by viktorasl** [comment]
Hey! Look at https://stripe.com/docs/terminal/payments:
> The PaymentIntent contains a client secret, a key that is unique to the individual PaymentIntent. To use the client secret, you must obtain it from the PaymentIntent on your server and pass it to the client side.

On your own back-end you have to create payment intent and then pass client secret to your front-end.

**Comment by mohamad-gadgetapp** [comment]
can we pay from your plugin ?

**Comment by viktorasl** [comment]
What do you mean? This plugin then has `confirmPayment` method which executes payment by client secret.
Plugin supports 3DS payments so UI asking for confirmation will be shown if needed

**Comment by lukebrandonfarrell** [comment]
@mohamad-gadgetapp To add to this, this does client side authentication, payment is taken from the server.

**Comment by viktorasl** [comment]
I think we've cleared all the thing, I'm closing it.
